channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=24.1
- pip:
  - mlflow==2.15.0
  - cloudpickle==2.2.0
  - numpy==1.24.4
  - psutil==5.9.3
  - scikit-learn==1.5.1
  - scipy==1.8.1
name: mlflow-env
